version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python django/manage.py makemigrations && python django/manage.py migrate && python django/manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db